version: 2
#orbs:
#  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/moody
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          PGHOST: localhost
          PGUSER: moody
          RAILS_ENV: test
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: moody
          POSTGRES_DB: moody_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - run:
          name: 'Update Node.js'
          command: |
            curl -sSL "https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v10.15.3-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash

      - run:
          name: Check current version of node
          command: node -v

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: moody-{{ checksum "Gemfile.lock" }}

      # install specific bundler
      - run: gem install bundler -v 2.1.4

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
#      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:create

      # Run the tests
      - run: yarn test

#      - run: bundle exec rspec/{controllers,api_acceptance}/

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
